name: Deploy Apps Script via CLASP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Debug Node version
        run: node -v

      - name: Install CLASP
        run: npm install -g @google/clasp

      - name: Authenticate with CLASP
        run: |
          echo "${{ secrets.CLASP_CREDENTIALS_JSON }}" > ~/.clasprc.json

      - name: Push to Apps Script
        run: clasp push
